graded_report_formatter/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("grf/", include("grf.urls")),
    path('admin/', admin.site.urls),
]

grf/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("report/<int:id>", views.ReportView.as_view(), name="report"),
    path('save_report/', views.save_report, name='save_report'),
    path('save_report_styling/<int:report_id>', views.save_report_styling, name='save_report_styling'),
    path('delete_report/<int:report_id>', views.delete_report, name='delete_report'),
    path("report/<int:id>/display", views.ReportDisplayView.as_view(), name="report-display"),
]

grf/models.py
from django.db import models
from django.utils import timezone


def get_report_styling_file_content():
    file_path = 'grf/static/grf/css/report-display.css'
    with open(file_path, 'r') as f:
        return f.read()

class Report(models.Model):
    title = models.CharField(max_length=100)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(default=timezone.now)
    template = models.ForeignKey('self', on_delete=models.DO_NOTHING, null=True)
    css_style = models.TextField(default=get_report_styling_file_content)

class ReportPart(models.Model):
    report = models.ForeignKey(Report, on_delete=models.CASCADE)
    order = models.PositiveIntegerField()
    is_graded = models.BooleanField(default=True)
    is_included = models.BooleanField(default=True)
    title = models.CharField(max_length=200)
    introduction = models.TextField(default='')

class ReportSubPart(models.Model):
    parent_part = models.ForeignKey(ReportPart, on_delete=models.CASCADE, null=True)
    parent_subpart = models.ForeignKey('self', on_delete=models.CASCADE, null=True)
    order = models.PositiveIntegerField(null=True)
    title = models.CharField(max_length=200)
    is_included = models.BooleanField(default=True)
    grade = models.PositiveIntegerField(null=True)
    introduction = models.TextField(default='')
    is_intro_included = models.BooleanField(default=True)
    content = models.TextField(default='')

grf/views.py
import json
from django.views import generic
import jsonschema
from jsonschema.exceptions import ValidationError
from .models import Report, ReportPart, ReportSubPart
from django.http import HttpRequest, JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.utils import timezone
from django.contrib.staticfiles.finders import find

class IndexView(generic.TemplateView):
    template_name = 'index.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['all_reports'] = Report.objects.all()
        return context

class ReportView(generic.DetailView):
    model = Report
    template_name = 'report/edit.html'
    
    def get_object(self, queryset=None):
        id = self.kwargs.get("id")
        return Report.objects.get(pk=id)
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['template_part'] = ReportPart(pk=None)
        context['template_subpart'] = ReportSubPart(pk=None)
        return context

class ReportDisplayView(generic.DetailView):
    model = Report
    template_name = 'report/display.html'
    
    def get_object(self, queryset=None):
        id = self.kwargs.get("id")
        return Report.objects.get(pk=id)

@csrf_exempt
def save_report(request:HttpRequest):
    if request.method == 'POST':
        request_body = json.loads(request.body.decode('utf-8'))
        dict_report = request_body.get('report', {})
        is_valide, validation_message = validate_json_report(dict_report)
        if not is_valide:
            return JsonResponse({'message': validation_message}, status=400)      
        
        if 'parts_to_remove' in dict_report:
            for id in dict_report['parts_to_remove']:
                ReportPart.objects.get(pk=id).delete()
        if 'subparts_to_remove' in dict_report:
            for id in dict_report['subparts_to_remove']:
                ReportSubPart.objects.get(pk=id).delete()
        
        if dict_report['id']:
            try:
                report = Report.objects.get(pk=dict_report['id'])
                report.title = dict_report['title']
                report.updated_at = timezone.now()
            except:
                return JsonResponse({'message': "No report found with id "+str(dict_report['id'])}, status=400)
        else:
            report = Report(title=dict_report['title'])
        report.save()
        
        for order, part in enumerate(dict_report['parts']):
            status, message = save_report_part(part, report, order)
            if not status:
                return JsonResponse({'message': message}, status=400)
        return JsonResponse({'message': 'Report saved', 'id':report.pk}, status=200)
    return JsonResponse({'message': 'Failed to save report'}, status=400)

@csrf_exempt
def delete_report(request, report_id):
    try:
        report = Report.objects.get(id=report_id)
        report.delete()
        return JsonResponse({'message': 'Report deleted successfully.'}, status=200)
    except Report.DoesNotExist:
        return JsonResponse({'message': 'Report not found.'}, status=404)

@csrf_exempt
def save_report_styling(request, report_id):
    if request.method == 'POST':
        request_body = json.loads(request.body.decode('utf-8'))
        css_style = request_body.get('style', {})
        if not css_style:
            return JsonResponse({'message': 'No style in request body'}, status=400)

        try:    
            report = Report.objects.get(id=report_id)
            report.css_style = css_style
            report.save()
            return JsonResponse({'message': 'Styling saved'}, status=200)
        except Report.DoesNotExist:
            return JsonResponse({'message': 'Report not found'}, status=400)

def validate_json_report(report:dict, schema_static_path:str='grf/validators/report-schema.json'):
    schema_path = find(schema_static_path)
    if not schema_path:
        raise FileNotFoundError('No file found at static path '+schema_static_path)
    with open(schema_path, 'r') as file:
        report_schema = json.load(file)
    try:
        jsonschema.validate(report, report_schema)
        return True, ''
    except ValidationError as e:
        return False, e.message
    
def save_report_part(dict_part: dict, report: Report, order):
    if dict_part['id']:
        try:
            report_part = ReportPart.objects.get(pk=dict_part['id'])
            if report.pk != report_part.report.pk:
                return False, "Report part "+str(report_part.pk)+" already associated to report "+str(report_part.report.pk)
        except:
            return False, "No report part found with id "+str(dict_part['id'])
    else:
        report_part = ReportPart(report=report)

    report_part.title = dict_part['title']
    report_part.is_graded = dict_part['is_graded']
    report_part.is_included = dict_part['is_included']
    report_part.introduction = dict_part['introduction']
    report_part.order = order
    report_part.save()
    
    for order, subpart in enumerate(dict_part['subparts']):
        status, message = save_report_subpart(subpart, order, parent_part=report_part)
        if not status:
            return False, message
    return True, ''

def save_report_subpart(dict_subpart : dict, order:int, parent_part:ReportPart=None, parent_subpart:ReportSubPart=None):
    if dict_subpart['id']:
        try:
            report_subpart = ReportSubPart.objects.get(pk=dict_subpart['id'])
        except:
            return False, "No report subpart found with id "+str(dict_subpart['id'])
        if parent_part and parent_part.pk != report_subpart.parent_part.pk:
            return False, "Report subpart "+str(report_subpart.pk)+" already associated to report part "+str(report_subpart.parent_part.pk)
        if parent_subpart and parent_subpart.pk != report_subpart.parent_subpart.pk:
            return False, "Report subpart "+str(report_subpart.pk)+" already associated to report subpart "+str(report_subpart.parent_subpart.pk)
    else:
        report_subpart = ReportSubPart()

    if parent_subpart:
        report_subpart.parent_subpart = parent_subpart
    if parent_part:
        report_subpart.parent_part = parent_part
    report_subpart.title = dict_subpart['title']
    report_subpart.grade = dict_subpart['grade']
    report_subpart.is_included = dict_subpart['is_included']
    report_subpart.is_intro_included = dict_subpart['is_intro_included']
    report_subpart.introduction = dict_subpart['introduction']
    report_subpart.content = dict_subpart['content']
    report_subpart.order = order
    report_subpart.save()
    
    for order, subpart in enumerate(dict_subpart['subparts']):
        status, message = save_report_subpart(subpart, order, parent_subpart=report_subpart)
        if not status:
            return False, message
    return True, ''

grf/templates/report/display.html
{% load static %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.8.0/html2pdf.bundle.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.63.0/codemirror.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.63.0/mode/css/css.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.63.0/addon/hint/show-hint.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.63.0/addon/hint/css-hint.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.63.0/addon/hint/show-hint.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.63.0/codemirror.min.css">

<link rel="stylesheet" href="{% static 'grf/css/toolbar.css' %}">
<link rel="stylesheet" href="{% static 'grf/css/modal.css' %}">

<script src="{% static 'grf/js/editable-style.js' %}" defer></script>
<script src="{% static 'grf/js/report-CRUD.js' %}" defer></script>
<script src="{% static 'grf/js/report-display.js' %}"></script>

<div id="toolbar" class="toolbar">
    <a href="/grf">Home</a>
    <div class="buttons">
        <button report-id="{{ report.id }}" report-title="{{ report.title }}" 
            onclick="exportToPDF(
                this.getAttribute('report-id'), 
                this.getAttribute('report-title'), false)">
            Export to PDF
        </button>
        <a href="/grf/report/{{ report.id }}">
            <button>Edit</button>
        </a>
        <button onclick="openModal()">Options</button>
    </div>
</div>

<div id="modal-container" class="modal">
    <div class="modal-content">
        <span class="close" onclick="closeModal()">&times;</span>
        <div id="editable-style">
            Document style:
            <style report-id="{{ report.id }}"></style>
            <textarea id="css-editor">{{ report.css_style }}</textarea>
            <button onclick="saveReportStyle()">Save style</button>
        </div>        
    </div>
</div>

<div id="table-of-contents"></div>
<div class="html2pdf__page-break"></div>
<div id="report-title">{{ report.title }}</div>
{% for report_part in report.reportpart_set.all|dictsort:"order" %}
    {% if report_part.is_included %}
        <div class="report-part" id="part-{{ report_part.id }}">
            <h1>
                <span class="section-number"></span>
                <span class="section-title">{{ report_part.title }}</span>
            </h1>
            <div class="content">
                <div class="part-content">{{ report_part.introduction|safe }}</div>
                {% if report_part.reportsubpart_set.all %}
                <div class="subparts">
                    {% for subpart in report_part.reportsubpart_set.all|dictsort:"order" %}
                        {% include "report/subpart-display.html" with subpart=subpart is_graded=report_part.is_graded depth=2 %}
                    {% endfor %}
                </div>  
                {% endif %}      
            </div>
        </div>
        <div class="html2pdf__page-break"></div>
    {% endif %}    
{% endfor %}

<script>initializeReportDisplay()</script>

grf/templates/report/edit.html
{% load static %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/jquery-ui.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.13.2/themes/base/jquery-ui.min.css">

<script src="https://cdn.ckeditor.com/ckeditor5/36.0.0/classic/ckeditor.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/2.5.1/jspdf.umd.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/dompurify/3.0.6/purify.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js"></script>

<script src="{% static 'grf/js/text-editor.js' %}" defer></script>
<script src="{% static 'grf/js/report-edit-setter.js' %}" defer></script>
<script src="{% static 'grf/js/json-report.js' %}" defer></script>
<script src="{% static 'grf/js/report-CRUD.js' %}" defer></script>

<link rel="stylesheet" href="{% static 'grf/css/styles.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'grf/css/toolbar.css' %}">
<link rel="stylesheet" href="{% static 'grf/css/report.css' %}">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

<div class="toolbar">
    <a href="/grf">Home</a>
    <div class="buttons">
        <button onclick="saveReport(reportToDict())">Save</button>
        <button onclick="exportToJSON()">Export to JSON</button>
        <a href="/grf/report/{{ report.id }}/display">        
            <button>HTML preview</button>
        </a>
        <button report-id="{{ report.id }}" report-title="{{ report.title }}" 
            onclick="exportToPDF(
                this.getAttribute('report-id'), 
                this.getAttribute('report-title'), true)">
            Export to PDF
        </button>
        <button>Export to WORD</button>
    </div>
</div>

<div class="accordion" id="report-accordion" object-id="{{ object.id }}">
    <input type="text" id="report-title" value="{{ object.title }}">
    {% for report_part in report.reportpart_set.all|dictsort:"order" %}
        {% include "report/part.html" with report_part=report_part %}
    {% endfor %}
    <button class="add-accordion-item add-part">+</button>
</div>
<div id="templates" style="display: none;">
    <div id="template-part">
        {% include "report/part.html" with report_part=template_part %}
    </div>
    <div id="template-direct-subpart">
        {% include "report/subpart.html" with subpart=template_subpart is_graded=True is_direct=True %}
    </div>
    <div id="template-subpart">
        {% include "report/subpart.html" with subpart=template_subpart %}
    </div>
</div>

grf/templates/report/part.html
<div class="accordion-item part-accordion-item" object-id="{{ report_part.id }}">
    <div class="accordion-header">
        <span class="accordion-drag-handle">&#9776;</span> 
        <input type="text" class="title" value="{{ report_part.title }}">
        <label for="grade-toggle-{{ report_part.id }}">Grade</label>
        <input type="checkbox" id="grade-toggle-{{ report_part.id }}" class="grade-toggle" {% if report_part.is_graded %}checked{% endif %}>                
        <label for="include-part-{{ report_part.id }}">Include</label>
        <input type="checkbox" id="include-part-{{ report_part.id }}" class="include" {% if report_part.is_included %}checked{% endif %}>
        <button class="delete delete-report-element delete-part"><i class="fas fa-trash-alt"></i></button>
        <button class="accordion-toggle">&#9660;</button>
    </div>
    <div class="accordion-content">
        <div class="text-editor" html-content="{{ report_part.introduction }}"></div>
        <div class="accordion" id="part-{{ report_part.id }}">
            {% if report_part.id %}
                {% for subpart in report_part.reportsubpart_set.all|dictsort:"order" %}
                    {% include "report/subpart.html" with subpart=subpart is_graded=report_part.is_graded is_direct=True %}
                {% endfor %}
            {% endif %}
            <button class="add-accordion-item add-direct-subpart">+</button>
        </div>
    </div>
</div>

grf/templates/report/subpart-display.html
{% if subpart.is_included %}
    <div class="report-part" id="subpart-{{ subpart.id }}">
        <h{{ depth }}>
            <span class="section-number"></span>
            <span class="section-title">{{ subpart.title }}</span>
            {% if is_graded and subpart.grade is not None %}
                <img class="grade-image" src="/static/grf/images/grade-{{ subpart.grade }}.png">
            {% endif %}
        </h{{ depth }}>
        {% if subpart.is_intro_included %}
            <div class="subpart-introduction">{{ subpart.introduction|safe }}</div>
        {% endif %}
        <div class="subpart-content">{{ subpart.content|safe }}</div>
        {% if subpart.reportsubpart_set.all %}
            <div class="subparts">
                {% for subpart in subpart.reportsubpart_set.all|dictsort:"order" %}
                    {% include "report/subpart-display.html" with subpart=subpart is_graded=False depth=depth|add:1 %}            
                {% endfor %}
            </div>  
        {% endif %}      
    </div>
{% endif %}  

grf/templates/report/subpart.html
<div class="accordion-item subpart-accordion-item" object-id="{{ subpart.id }}">
    <div class="accordion-header">
        <span class="accordion-drag-handle">&#9776;</span> 
        <input type="text" class="title" value="{{ subpart.title }}">
        {% if is_direct %}
            <label for="grade-{{ subpart.id }}" class="grade-label" {% if not is_graded %}style="display: none;"{% endif %}>Grade</label>
            <select id="grade-{{ subpart.id }}" class="grade-select" value="{{ subpart.grade }}" {% if not is_graded %}style="display: none;"{% endif %}>
                <option value="empty"></option>
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
            </select>
        {% endif %}
        <label for="include-subpart-{{ subpart.id }}">Include</label>
        <input type="checkbox" id="include-subpart-{{ subpart.id }}" class="include" {% if subpart.is_included %}checked{% endif %}>
        <button class="delete delete-report-element delete-subpart"><i class="fas fa-trash-alt"></i></button>
        <button class="accordion-toggle">&#9660;</button>
    </div>
    <div class="accordion-content">
        <div class="introduction">
            Introduction
            <input type="checkbox" title="include" class="intro-include" value="{{ subpart.is_intro_included }}">                
            <button class="hide-show-subpart-intro">Show</button>  
            <div class="introduction-content" style="display: none;">
                <div class="text-editor" html-content="{{ subpart.introduction }}"></div>
            </div>      
        </div>
        <div class="text-editor" html-content="{{ subpart.content }}"></div>
        <div class="accordion" id="subpart-{{ subpart.id }}">
            {% if subpart.id %}
                {% for subpart in subpart.reportsubpart_set.all|dictsort:"order" %}
                    {% include "report/subpart.html" with subpart=subpart is_graded=false %}
                {% endfor %}
            {% endif %}
            <button class="add-accordion-item add-subpart">+</button>
        </div>
    </div>
</div>